### ISSUE TITLE
eless: Doesn't preserve view-mode when opening file from dired

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/eless#1]
As posted by @alphapapa [here][1]:

> If I do `eless .`, and then open a file from the dired buffer, it's no longer in view mode. :)

[1]: https://github.com/kaushalmodi/.emacs.d/issues/26

**Comment by kaushalmodi** [comment]
Strange that you mention that :)

I am [specifically][1] disabling `view-mode` if `dired-mode` is detected. My main reason for doing that is because the `view-mode-map` keys shadowed many useful bindings in `dired-mode-map`. As `dired-mode` is anyways a `special-mode`, it is "read-only" by default (i.e. it is not a normal editable file buffer), there is no need to enable `view-mode`.

I though have a feeling why this question was raised.. hitting `q` does not seem to behave as a "less" substitute if the mode is `dired-mode`. I have fixed that in https://github.com/kaushalmodi/eless/commit/7a0f7410ae2bb082cf1283742bb9540b72d9b84f.

```el
(define-key dired-mode-map (kbd "q") (quote save-buffers-kill-emacs))
```

[1]: https://github.com/kaushalmodi/eless/blob/7a0f7410ae2bb082cf1283742bb9540b72d9b84f/eless#L298-L306

**Comment by alphapapa** [comment]
Hm, well, what I mean is, if I'm thinking of eless as a "better less," then when I use it to view a file from its built-in dired mode, I would expect it to view that file in a read-only view mode, not regular Emacs editor mode.  :)

> I though have a feeling why this question was raised.. hitting q does not seem to behave as a "less" substitute if the mode is dired-mode. I have fixed that in 7a0f741.

That's a good idea.

**Comment by kaushalmodi** [comment]
But the dired-mode *is* a read-only mode. It becomes "writeable" only when wdired is enabled.

**Comment by alphapapa** [comment]
Sorry, what I mean is:

1.  User runs `eless .`, which opens a dired buffer.
2.  User presses `RET` on a text file (not necessarily `txt`).
3.  The file is now opened in normal, writable mode.  This seems contrary to the purpose of `eless`, to *view* files, and to require manual intervention to disable `read-only-mode`.

**Comment by kaushalmodi** [comment]
Thanks for that explanation..

If I bind RET to `dired-view-file` (bound to `v` by default), would that work?

**Comment by kaushalmodi** [comment]
Try updating to the latest https://github.com/kaushalmodi/eless/commit/e5f53639cc5c5366c58e7095ba8bebc9483de6f0

**Comment by alphapapa** [comment]
Thanks, that's great.

**Comment by kaushalmodi** [comment]
Thanks. You might like the new `q` binding with this change too ( https://github.com/kaushalmodi/eless/commit/2f23f9c9f9a0bbbdc28cc024c16a4137a22e7732 ). I made commits in the wrong order.. this commit was made before the above referenced, but it makes more sense in the reverse order.

**Comment by kaushalmodi** [comment]
@alphapapa I believe this issue is fixed. Feel free to re-open it if needed.
