### ISSUE TITLE
Don't use grep -P

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/eless#19]
Copied https://github.com/kaushalmodi/eless/issues/18#issuecomment-365426688 by @sshaw below verbatim:

---

If adaptation is a goal, I would not require GNU grep and would use an alternate approach.
It seems as though you're using `-P` just for regex lookahead. 

There are alternatives (untested 😄):

```
grep -o '^([A-Za-z-_]+\([0-9]+\))(?=\s+.*?\1$)' 
```

Can be:

```
grep '^\([A-Za-z_-]+([0-9]+)\) \+.*\1$'  | grep -o '^[A-Za-z_-]\+([0-9]\+)'
```

Or instead of using Perl regexes (`-P`), just use perl:

```
perl -ne'/^([A-Za-z-_]+\([0-9]+\))(?=\s+.*?\1$)/ and print'
```

It's likely already installed and I'm pretty sure it's installed by default more than GNU grep. 

Also if you use `egrep` then you don't have to escape any of `()+`. 

---

**Comment by kaushalmodi** [comment]
> Or instead of using Perl regexes (-P), just use perl

That's interesting.. didn't think of that.

> Also if you use egrep then you don't have to escape any of ()+.

I believe it's more canonical to use `grep -E` instead of `egrep`? In any case, I first became a fan of `grep -E` (and `sed -r`) and then `grep -P`.

I'll have to find some time to research replacing the `grep -P` and `sed -r`.

Thanks for all that info.

**Comment by sshaw** [comment]
> I believe it's more canonical to use grep -E instead of egrep?

Not sure.

**Comment by kaushalmodi** [comment]
> Note sure

Oh well, from `man grep` (of course GNU grep):

>     In addition, two variant programs egrep and fgrep are available.  egrep is
>      the  same as grep -E.  fgrep is the same as grep -F.  Direct invocation as
>      either egrep or fgrep is deprecated, but is provided to  allow  historical
>      applications that rely on them to run unmodified.

**Comment by kaushalmodi** [comment]
I'll need to spend some time understanding how to convert `grep -Po ..` expressions to `perl -ne ..`.

Help me out if you already have the answer :)

```
> echo "Help on Quitter in module _sitebuiltins object:" | \grep -Po '^Help on (.+ in )*(module|package) \K(.*)(?=:$)'
_sitebuiltins object

> echo "Help on Quitter in module _sitebuiltins object:" | \perl -ne '/^Help on (.+ in )*(module|package) \K(.*)(?=:$)/ and print'
Help on Quitter in module _sitebuiltins object:
```

Need to figure out out to make `perl` return only the stuff **after `\K** and **before `(?= .. )`** (that's what the `-o` in `grep` does.. and the `-P` makes it understand `\K` and look-ahead).

**Comment by kaushalmodi** [comment]
OK, this worked:

```
echo "Help on Quitter in module _sitebuiltins object:" | \perl -ne '/^Help on (.+ in )*(module|package) (.*)(?=:$)/ and print "$3"'
```

**Comment by kaushalmodi** [comment]
Please test the [`replace-grep-with-perl`][1] branch.

[1]: https://github.com/kaushalmodi/eless/tree/replace-grep-with-perl

**Comment by sshaw** [comment]
Working!

Note that `$3` does not need to be quoted. 

You also can use non-capturing parenthesis around the groups you don't want to capture, then use `print $1`:

```
perl -ne '/^Help on (?:.+ in )*(?:module|package) (.*)(?=:$)/ and print $1'
```

Just an FYI.

**Comment by kaushalmodi** [comment]
> Note that $3 does not need to be quoted. You also can use non-capturing parenthesis around the groups you don't want to capture,

Thanks, of course. Completely forgot that elisp regexp is not the only place you could do that :)
