### ISSUE TITLE
Replace sed -r s/foo/bar/I with BSD compatible equivalent

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/eless#23]
From https://github.com/kaushalmodi/eless/issues/18#issuecomment-365426688:

>`sed -r` and the regex option `I` are GNU specific as well.  And in [this case](https://github.com/kaushalmodi/eless/blob/308c6e76d0935c887087f2a6ec5a7433caaf3798/eless#L505) you can achieve the same thing with Bash variable expansion: 
 
>```bash
>some_var=${some_var/bash_builtins/builtins}
>```

**Comment by kaushalmodi** [comment]
@sshaw Can you try from the latest master.. the `sed` issue should at least be fixed.

**Comment by sshaw** [comment]
Working!
