### ISSUE TITLE
Fix building using "make all" on macOS

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/eless#24]
@sshaw

The "eless build requirements" are higher than "eless run requirements".

For future plans like auto-publishing `eless` documentation site using `ox-hugo`, the minimum requirement for building eless script and documentation is emacs 24.4.. Couple of reasons:
- I use Org `master` (9.2.x), but can make sure that builds work fine on latest Org stable (9.1.x) too.. Minimum requirement for Org 9.1.x is emacs 24.4. **So not worth trying to make the build process work on older emacs/Org versions.**
- In the `ox-hugo` build setup, I use `advice-add` which got added in emacs 24.4. 

From your [comment in other thread][1]:

> >make all EMACS=Emacs
>
>      /tmp/eless >make all EMACS=Emacs
>      Emacs binary used: Emacs
>      Loading /tmp/eless/build/setup-eless.el (source)...
>      Emacs is now refreshing its package database...
>      Importing package-keyring.gpg...
>      Importing package-keyring.gpg...done
>      Contacting host: orgmode.org:443
>      Failed to download ‘org’ archive.
>      Failed to download ‘melpa’ archive.
>      Package refresh done
>      Installing ‘org-plus-contrib’ ..
>      Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
>      Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
>      Package ‘org-plus-contrib-’ is unavailable
>      make: *** [vcheck] Error 255

**What emacs version was that?**

The failure seems odd that it failed in the package download step itself.. http/https issues?

Let's first get `make vcheck` working on your system, **emacs 24.4** or newer.

[1]: https://github.com/kaushalmodi/eless/issues/20#issuecomment-365614363

**Comment by sshaw** [comment]
> make all EMACS=Emacs

```
/tmp/eless >Emacs --version
GNU Emacs 25.3.1
Copyright (C) 2017 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
```
/tmp/eless >make vcheck
Emacs binary used: /Applications/Emacs.app/Contents/MacOS/Emacs
Loading /tmp/eless/build/setup-eless.el (source)...
Emacs is now refreshing its package database...
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: orgmode.org:443
Failed to download ‘org’ archive.
Failed to download ‘melpa’ archive.
Package refresh done
Installing ‘org-plus-contrib’ ..
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
Package ‘org-plus-contrib-’ is unavailable
make: *** [vcheck] Error 255
```

**Comment by kaushalmodi** [comment]
Thanks. Do you want to hack `build/setup-eless.el` locally and see if forcing http instead of https helps? 

[These lines][1]

[1]: https://github.com/kaushalmodi/eless/blob/9b83a2643c503ec73250960038a3cd7c17c92bcb/build/setup-eless.el#L109-L117

**Comment by kaushalmodi** [comment]
Or may be launch `Emacs -Q` and manually eval the sexps in that setup file responsible for downloading those packages? I don't have a clue why the basic package installation would fail.. That package installation happens every time on Netlify each time https://eless.scripter.co/ deploys.

**Comment by kaushalmodi** [comment]
.. and [here's the package installation on emacs 25.3 on Travis][1].. so what is so OS specific in that setup file ..

[1]: https://travis-ci.org/kaushalmodi/eless/jobs/341672602

**Comment by sshaw** [comment]
Found the problem: `network-security-level` was set to `medium`. This prompts one before connections are made. Setting this to `low` [here](https://github.com/kaushalmodi/eless/blob/9b83a2643c503ec73250960038a3cd7c17c92bcb/Makefile#L83) fixed it. 

Not sure if there are other solutions.

**Comment by kaushalmodi** [comment]
Interesting.. so you are prompted each time you install/upgrade a package?

**Comment by sshaw** [comment]
I use Cask so my installing is done outside emacs. In the cases when I do inside installing it's done via Try and yes, I'm prompted.

**Comment by sshaw** [comment]
Well, I prompted for the host if I haven't been prompted in sometime. Not sure what that is. Seems to be weeks.

**Comment by kaushalmodi** [comment]
>Found the problem: network-security-level was set to medium. This prompts one for confirmation before connections are made.

The default value of this variable (which got introduced in emacs 25.1) is `'medium`, and it works fine i.e. I don't get any extra prompt on RHEL 6.6 (or any GNU Linux image on Gitlab Pages/Netlify/Travis). So it's likely that there's something special with macOS?

>Setting this to low [here][1] fixed it.

Let me create a trial branch where I set that var to low only if the OS is macOS.

[1]: https://github.com/kaushalmodi/eless/blob/9b83a2643c503ec73250960038a3cd7c17c92bcb/Makefile#L83

**Comment by kaushalmodi** [comment]
Please try this branch: https://github.com/kaushalmodi/eless/tree/macOS-lower-network-security

**Comment by sshaw** [comment]
That branch works. 

On OS X is may be due to the cert store not containing the CA's cert.

**Comment by kaushalmodi** [comment]
This too merged into master.
