### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by mobyte0** [kaushalmodi/eless#29]
Hey, let's talk about the current theme.

I like the new ([9448563](https://github.com/kaushalmodi/eless/commit/94485630bfc42f384597dc563c3b616243613042)) `Man-overstrike` color but I don't think it meshes well with `man` links. In my opinion (by using this site: http://paletton.com/#uid=51v0u0kkOuvb3MlgsBnparKsemh), I think #F3C355 would be a well suited color. I also think that talking about the default menu bar colors would be worth a discussion.

I tried to add this myself with a pull request but for some reason it wouldn't recognize me setting the face.

Thoughts?

**Comment by kaushalmodi** [comment]
> but I don't think it meshes well with man links.
> In my opinion (by using this site: http://paletton.com/#uid=51v0u0kkOuvb3MlgsBnparKsemh), I think #F3C355 would be a well suited color. 

I don't quite get that, but I am fine with that color too. Can you provide a screenshot to explain what you mean by the color not meshing well with the links?

Also, you can get the same change by putting below in your `~/.emacs.d/elesscfg`:

```elisp
;; -*- emacs-lisp -*-
(load-theme (quote tango-dark) :no-confirm)
;; The tango-dark theme is good except for the bright yellow hl-line face
(custom-theme-set-faces
 (quote user)
 (quote (hl-line ((t (:background "color-238")))))
 (quote (Man-overstrike ((t (:foreground "#f3c355" :weight normal))))))
```

Above will load the current default theme + your suggested color.

> I also think that talking about the default menu bar colors would be worth a discussion.

We can heavily customize the whole theme, or selected faces, but you can do that in your custom `elesscfg` too. You can start with the above example.

**Comment by kaushalmodi** [comment]
Closing this issue as the default eless theme can be overridden in `~/.emacs.d/elesscfg`: https://eless.scripter.co/#user-config-override.
