### ISSUE TITLE
Any reason GUI mode is forced for man pages and the like?

### ISSUE THREAD

**Issue by itamarst** [kaushalmodi/eless#3]
It'd be nice if `eless` could be set to always use console or alway use GUI, I found the seemingly random choice of one or the other confusing.

**Comment by kaushalmodi** [comment]
This has been fixed few minutes back (https://github.com/kaushalmodi/eless/commit/943a513187d4f21622375d669dd20824f2458c00).

Earlier the limitation was the `emacs -Q -nw` could not received input from the pipe. `man` always sends data to the end process like `less` (`$PAGER`) via a pipe. So the same limitation applied.

This has now been fixed. Please git pull again and let me know if it works.

> could be set to always use console or alway use GUI,

Now by default, `eless` always opens in terminal mode. If you like to force GUI mode, pass the `-gui` switch.

**Comment by itamarst** [comment]
With latest version for `PAGER=eless man grep` I am getting console emacs... but split into two panes.

**Comment by kaushalmodi** [comment]
![mangrep](https://cloud.githubusercontent.com/assets/3578197/25404273/3fcf4454-29cd-11e7-8c22-11d686e036de.gif)


As we cannot pass the `-D` flag for `eless` directly to `man grep`, set `PAGER` to `eless -D`.

- I do not see `man` started with split windows. What emacs version are you on? I am on the latest build of emacs.
- Here is the debug info I get:

```
> man grep
--> Input from pipe/file
    Output to terminal -->
var : -D
Raw Args      : -D
Emacs Args    : -nw
Pipe Contents : GREP(1)                                                                GREP(1)
<snip -- The whole of grep man page>
Temp File : /tmp/emacs-stdin-kmodi.5MB8HSR
first_line_piped_data = GREP(1)                                                                GREP(1)
Man Page = GREP(1)
Eless Command : emacs_Q_view_mode                          -nw                          --eval '(progn
                                   (man (downcase "GREP(1)"))
                                   (delete-window)
                                 )'
Args passed to emacs_Q_view_mode : -nw --eval (progn
                                   (man (downcase "GREP(1)"))
                                   (delete-window)
                                 )
```

**Comment by itamarst** [comment]
24.5.1. Running inside tmux. Here's output:

```
Temp File : /tmp/emacs-stdin-itamarst.w9IDUzm
first_line_piped_data = GREP(1)                                                                                     General Commands Manual                                                                                    GREP(1)
Man Page = GREP(1)
Eless Command : emacs_Q_view_mode                          -nw                          --eval '(progn
                                   (man (downcase "GREP(1)"))
                                   (delete-window)
                                 )'
Args in emacs_Q_view_mode : -nw --eval (progn
                                   (man (downcase "GREP(1)"))
                                   (delete-window)
                                 )
```

**Comment by kaushalmodi** [comment]
> 24.5.1

I sorted of guessed that. The good news is that this issue has long been fixed. I would suggest that you upgrade to the recently released emacs 25.2.

I verified that the issue you mentioned happens on 24.5, but not on 25.1.

I'll still try fixing this so that it behaves the same for emacs 24.5 too.

**Comment by itamarst** [comment]
OK, thanks! I've been thinking about upgrading to latest Ubuntu, might be the excuse I need.

**Comment by kaushalmodi** [comment]
Let me know if this fixes the issue for you: https://github.com/kaushalmodi/eless/commit/57668b7eb944d2a4059587ae25221e3730a60790

**Comment by itamarst** [comment]
Now it starts with two panes and then jumps into having only one after a moment. I should probably just upgrade to newer version of Emacs...

Thanks for the help, and for the neat tool!

**Comment by kaushalmodi** [comment]
> Now it starts with two panes and then jumps into having only one after a moment.

Yeah, it's just a workaround.. I'll come back to this if I find a better way of fixing this.

> Thanks for the help, and for the neat tool!

Glad to help!
