### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by raxod502** [kaushalmodi/eless#30]
I cannot find any installation instructions in the documentation for `eless`. I eventually just cloned the repository and linked the `eless` script into my `PATH` (although the Info page is still not installed), but I'd rather this were spelled out so I didn't have to think about it. Or if there were a Homebrew formula for `eless`, that would solve the problem as well.

**Comment by kaushalmodi** [comment]
Thanks! I thought something was still missing :)

I am not a build-script expert (i.e. don't want to risk messing up people's directories). But considering the manual steps are not too complicated, would this work?: https://eless.scripter.co/#installation

**Comment by kaushalmodi** [comment]
> Or if there were a Homebrew formula for eless

I use RHEL 6.6, but if you know how to do that, PR is welcome.

**Comment by raxod502** [comment]
Thanks, the installation instructions are very helpful. Exactly what I was looking for.

Regarding a Homebrew formula, I have created one [here](https://github.com/raxod502/homebrew-core/blob/55bb7203272e83cf84e311a40578f112135e4d75/Formula/eless.rb). The only additional thing that is needed is a better test (see the `test do` section). Usually Homebrew prefers to have a test that actually tests basic functionality (e.g. for a C compiler, compile a "hello world" program). Any ideas? After that I can submit a pull request to Homebrew to get the formula merged, and installation will just be

```
brew install eless
```

**Comment by kaushalmodi** [comment]
> Exactly what I was looking for.

Thanks!

> I have created one here.

Thanks again :)

> The only additional thing that is needed is a better test (see the test do section). Usually Homebrew prefers to have a test that actually tests basic functionality (e.g. for a C compiler, compile a "hello world" program). Any ideas?

eless is an interactive program, requires `q` to quit. I am also not sure what kind of test would work that. Showing eless version as you did seems like the best thing right now.

**Comment by raxod502** [comment]
See https://github.com/Homebrew/homebrew-core/pull/24492.

**Comment by raxod502** [comment]
As per https://github.com/Homebrew/homebrew-core/pull/24492#discussion_r171456328, are there any particular version requirements on Bash and Perl?

**Comment by kaushalmodi** [comment]
I have tested on Perl 5.16.3, and [someone else has tested it on Bash 3.2][1].

I don't think I am using any esoteric syntax for either of those. So I don't think they can be specified as *minimum* versions. 

What are the versions on your OS (or the oldest macOS that you can get access to) where eless runs fine?

But if you really have to specify the minimum versions, then just set those.

[1]: https://github.com/kaushalmodi/eless/issues/27#issuecomment-367517199

**Comment by raxod502** [comment]
OK, well Perl 5.16.3 and Bash 3.2 happen to be exactly the versions shipped with OS X 10.10, the oldest version supported by Homebrew, so I'll remove the dependencies. Thanks!

**Comment by kaushalmodi** [comment]
I had forgotten to close this issue. It was resolved once I published https://eless.scripter.co/#installation.

**Comment by raxod502** [comment]
Might it be a good idea to put in a mention of Homebrew at the very top? It is always better to install software with a package manager than otherwise.

**Comment by kaushalmodi** [comment]
> Might it be a good idea to put in a mention of Homebrew at the very top?

I do not use homebrew, so it didn't make sense for me to put it at the very top. Though, I did add a section on how to install eless for homebrew users: https://eless.scripter.co/#installation-homebrew.

My preferred and tested installation procedure is now using `make install`: https://eless.scripter.co/#run-make.

**Comment by raxod502** [comment]
I strongly believe that installing software manually (for example, with `make install`) is an antipattern and shouldn't be recommended. Package managers came about for a reason: installing software in a standard and secure way, allowing for uninstallation, protecting users and maintainers from mistakes, and so on.

If you would prefer to keep it this way, though, I won't argue with you. It's your project.

**Comment by kaushalmodi** [comment]
@raxod502 I am not arguing the security and convenience of utilities like Homebrew. It's just that I do not have that installed at work (my primary machine). I am just accustomed to installing software locally in my `$HOME` and then managing versions of various apps using GNU Stow. Regular installation areas like `/usr/local` are not accessible to me. So `make install PREFIX=..` has become very natural to me.

It's just on principal that I cannot recommend or make an installation the primary method which I have never used. 

*I might be wrong but I thought that Homebrew was a macOS utility for the longest time, and I have never used a macOS system before. So I never felt the need to try it out. It's only recently that I see that now Homebrew is for Linux systems too.*

**Comment by kaushalmodi** [comment]
OK, I thought let me at least read through the Homebrew installation instructions on https://docs.brew.sh/Homebrew-on-Linux, and was disappointed to see this requirement:

> Glibc 2.13 or newer

I am on RHEL 6.8 which is Glibc 2.12. But this is not the first time that I am unable to use a distributed binary because of this Glibc issue, so I am used to doing `configure && make install` for almost everything ;-)

**Comment by raxod502** [comment]
I wasn't suggesting that Homebrew be used on a Linux system. I think that's also an antipattern except in niche use cases. Ideally, eless would be installed with the host system's native package manager. I personally run Manjaro Linux, so I would be installing using Pacman.

**Comment by kaushalmodi** [comment]
> Ideally, eless would be installed with the host system's native package manager.

For the same reason that **nothing** on my machine except to `/home/$USER/` is accessible to me, the OS's package manager does not work for me.

**Comment by raxod502** [comment]
Right, sure, I understand that you can't do it this way. It's for that reason that I think work computers where you don't have root access are also an antipattern. There are better and worse solutions to your situation, but there's also a sense in which it's just rearranging deck chairs on the Titanic.

My point is that _in general_, the standard, recommended solution for software installation should be the system package manager. And if there's a situation where that doesn't work, it should be communicated that there's something wrong with the situation.

Of course I also understand that none of this helps you in particular, because sometimes you just need to deal with the mess that somebody else created, but I think it's worth making a statement about the principle.
