### ISSUE TITLE
Customize faces

### ISSUE THREAD

**Issue by jsyjr** [kaushalmodi/eless#36]
Using elesss would be less jarring if it followed the custom-set-faces in my custom-file.

**Comment by kaushalmodi** [comment]
You should be able to add any customization in the user config override. Have you looked at: https://eless.scripter.co/#user-config-override ?

**Comment by kaushalmodi** [comment]
@jsyjr I have now added a little example to the eless docs to address your question: https://eless.scripter.co/#elesscfg-example--using-custom-file

**Comment by jsyjr** [comment]
Thanks.  The little example was just the clue I needed.  It works just as I had hoped.
