### ISSUE TITLE
`make install` fails without meaningful error message if makeinfo is not installed

### ISSUE THREAD

**Issue by t-qnective** [kaushalmodi/eless#37]
(Thanks for eless!)

```
Processing Texinfo file /home/tobias.rittweiler/Srcs/open-source/eless.git/docs/eless.texi...
File "/home/tobias.rittweiler/Srcs/open-source/eless.git/docs/eless.info" wasn’t produced.  See "*Org INFO Texinfo Output*" for details
make: *** [Makefile:58: emacs_batch] Error 255
```

When not running emacs in batch mode and looking into the mentioned buffer, one can discover that the `makeinfo` command is missing.

Suggestions:

1. Add `texinfo` under Requirements.
2. Check explicitly for the presence of `makeinfo` and fail with a meaningful error message.

**Comment by kaushalmodi** [comment]
> (Thanks for eless!)

Thank you :)

I will commit something shortly that fixes this. Your suggestions make a very good sense.

**Comment by kaushalmodi** [comment]
@t-qnective 

Please try out the latest commit on master.

Even though this issue is auto-closed, feel free to comment here further if you still see any issue.
