### ISSUE TITLE
Error when filename has parentheses

### ISSUE THREAD

**Issue by kolewu** [kaushalmodi/eless#38]
When loading a file and the filename has parentheses *eless* breaks with an error.

```bash
echo "no content" > "filename with (parentheses)".txt
LANGUAGE=C eless filename\ with\ \(parentheses\).txt
```

Result:
```
/usr/bin/eless: eval: line 684: syntax error near unexpected token `('
```

eless is
```
eless_version='v0.6'
eless_git_hash='1a21b4b'
```

**Comment by kaushalmodi** [comment]
I can accept a PR that fixes this. I don't know how to make bash interpret the whole escaped space string as a single string when pass it on to the emacs call.

One way to make it work is to use double quotes around the name with spaces.

e.g. `eless "filename\ with\ \(parentheses\).txt"`

**Comment by kaushalmodi** [comment]
The fix was actually simple. I have fixed this in 

https://github.com/kaushalmodi/eless/blob/2ee16ce79ef994bb62acc1db8a48d8ae68cf9dd6/eless.org#L602-L605

**Comment by kaushalmodi** [comment]
Now both of these work:

```
eless filename\ with\ \(parentheses\).txt
eless "filename with (parentheses).txt"
```
