### ISSUE TITLE
Auto-detect ANSI codes

### ISSUE THREAD

**Issue by kaushalmodi** [kaushalmodi/eless#6]
Parse the first few lines (may be 10?) to see if the file contains ANSI codes. If found, call the `ansi-color-apply-on-region` .

Probably remove the `-ansi` switch after that?

**Comment by alphapapa** [comment]
Would you consider using long-style options, i.e. `--ansi` instead of `-ansi`?

**Comment by kaushalmodi** [comment]
> Would you consider using long-style options, i.e. --ansi

Ah, I forgot about that, I will switch to long style option for `--gui` too. And if the auto-detection works well for ANSI, may be not have that option at all. WDYT?

**Comment by alphapapa** [comment]
Thanks.

Yeah, I'd say that if the auto-detection works, maybe make it the default and have an option to disable it.  Or just no option at all; if someone really needs to debug terminal control codes, this tool probably doesn't need to optimize for that.  :)

**Comment by kaushalmodi** [comment]
- Now the ANSI codes are auto-detected.
- `--ansi` switch is removed; not needed.

https://github.com/kaushalmodi/eless/commit/e327933885ae01342a58740d6684cf93bef20543
